"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

import builtins

from pydantic import Field

from githubkit.compat import GitHubModel, model_rebuild
from githubkit.typing import Missing
from githubkit.utils import UNSET

from .group_0118 import RepositoryRulesetConditions
from .group_0726 import (
    WebhookRepositoryRulesetEditedPropChangesPropConditionsPropUpdatedItems,
)


class WebhookRepositoryRulesetEditedPropChangesPropConditions(GitHubModel):
    """WebhookRepositoryRulesetEditedPropChangesPropConditions"""

    added: Missing[builtins.list[RepositoryRulesetConditions]] = Field(default=UNSET)
    deleted: Missing[builtins.list[RepositoryRulesetConditions]] = Field(default=UNSET)
    updated: Missing[
        builtins.list[
            WebhookRepositoryRulesetEditedPropChangesPropConditionsPropUpdatedItems
        ]
    ] = Field(default=UNSET)


model_rebuild(WebhookRepositoryRulesetEditedPropChangesPropConditions)

__all__ = ("WebhookRepositoryRulesetEditedPropChangesPropConditions",)
