"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

import builtins

from pydantic import Field

from githubkit.compat import GitHubModel, model_rebuild
from githubkit.typing import Missing
from githubkit.utils import UNSET


class RepositoryRulesetConditionsRepositoryIdTargetPropRepositoryId(GitHubModel):
    """RepositoryRulesetConditionsRepositoryIdTargetPropRepositoryId"""

    repository_ids: Missing[builtins.list[int]] = Field(
        default=UNSET,
        description="The repository IDs that the ruleset applies to. One of these IDs must match for the condition to pass.",
    )


model_rebuild(RepositoryRulesetConditionsRepositoryIdTargetPropRepositoryId)

__all__ = ("RepositoryRulesetConditionsRepositoryIdTargetPropRepositoryId",)
