"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

import builtins

from pydantic import Field

from githubkit.compat import GitHubModel, model_rebuild

from .group_0035 import OrganizationSimple


class EnterprisesEnterpriseActionsPermissionsOrganizationsGetResponse200(GitHubModel):
    """EnterprisesEnterpriseActionsPermissionsOrganizationsGetResponse200"""

    total_count: float = Field()
    organizations: builtins.list[OrganizationSimple] = Field()


model_rebuild(EnterprisesEnterpriseActionsPermissionsOrganizationsGetResponse200)

__all__ = ("EnterprisesEnterpriseActionsPermissionsOrganizationsGetResponse200",)
