"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

import builtins
from typing import Union

from pydantic import Field

from githubkit.compat import GitHubModel, model_rebuild
from githubkit.typing import Missing
from githubkit.utils import UNSET

from .group_0002 import SimpleUser
from .group_0009 import Integration
from .group_0064 import Team


class ProtectedBranchPropRequiredPullRequestReviewsPropDismissalRestrictions(
    GitHubModel
):
    """ProtectedBranchPropRequiredPullRequestReviewsPropDismissalRestrictions"""

    url: str = Field()
    users_url: str = Field()
    teams_url: str = Field()
    users: builtins.list[SimpleUser] = Field()
    teams: builtins.list[Team] = Field()
    apps: Missing[builtins.list[Union[Integration, None]]] = Field(default=UNSET)


class ProtectedBranchPropRequiredPullRequestReviewsPropBypassPullRequestAllowances(
    GitHubModel
):
    """ProtectedBranchPropRequiredPullRequestReviewsPropBypassPullRequestAllowances"""

    users: builtins.list[SimpleUser] = Field()
    teams: builtins.list[Team] = Field()
    apps: Missing[builtins.list[Union[Integration, None]]] = Field(default=UNSET)


model_rebuild(ProtectedBranchPropRequiredPullRequestReviewsPropDismissalRestrictions)
model_rebuild(
    ProtectedBranchPropRequiredPullRequestReviewsPropBypassPullRequestAllowances
)

__all__ = (
    "ProtectedBranchPropRequiredPullRequestReviewsPropBypassPullRequestAllowances",
    "ProtectedBranchPropRequiredPullRequestReviewsPropDismissalRestrictions",
)
