"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

import builtins
from typing import Literal, Union
from typing_extensions import NotRequired, TypedDict


class CustomPropertySetPayloadType(TypedDict):
    """Custom Property Set Payload

    Custom property set payload
    """

    value_type: Literal["string", "single_select", "multi_select", "true_false"]
    required: NotRequired[bool]
    default_value: NotRequired[Union[str, builtins.list[str], None]]
    description: NotRequired[Union[str, None]]
    allowed_values: NotRequired[Union[builtins.list[str], None]]


__all__ = ("CustomPropertySetPayloadType",)
