"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

import builtins
from typing_extensions import NotRequired, TypedDict

from .group_0118 import RepositoryRulesetConditionsType
from .group_0726 import (
    WebhookRepositoryRulesetEditedPropChangesPropConditionsPropUpdatedItemsType,
)


class WebhookRepositoryRulesetEditedPropChangesPropConditionsType(TypedDict):
    """WebhookRepositoryRulesetEditedPropChangesPropConditions"""

    added: NotRequired[builtins.list[RepositoryRulesetConditionsType]]
    deleted: NotRequired[builtins.list[RepositoryRulesetConditionsType]]
    updated: NotRequired[
        builtins.list[
            WebhookRepositoryRulesetEditedPropChangesPropConditionsPropUpdatedItemsType
        ]
    ]


__all__ = ("WebhookRepositoryRulesetEditedPropChangesPropConditionsType",)
