"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

import builtins
from typing_extensions import NotRequired, TypedDict

from .group_0010 import WebhookConfigType


class ReposOwnerRepoHooksHookIdPatchBodyType(TypedDict):
    """ReposOwnerRepoHooksHookIdPatchBody"""

    config: NotRequired[WebhookConfigType]
    events: NotRequired[builtins.list[str]]
    add_events: NotRequired[builtins.list[str]]
    remove_events: NotRequired[builtins.list[str]]
    active: NotRequired[bool]


__all__ = ("ReposOwnerRepoHooksHookIdPatchBodyType",)
