"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

import builtins
from typing_extensions import NotRequired, TypedDict


class ApiOverviewType(TypedDict):
    """Api Overview

    Api Overview
    """

    verifiable_password_authentication: bool
    ssh_key_fingerprints: NotRequired[ApiOverviewPropSshKeyFingerprintsType]
    ssh_keys: NotRequired[builtins.list[str]]
    hooks: NotRequired[builtins.list[str]]
    github_enterprise_importer: NotRequired[builtins.list[str]]
    web: NotRequired[builtins.list[str]]
    api: NotRequired[builtins.list[str]]
    git: NotRequired[builtins.list[str]]
    packages: NotRequired[builtins.list[str]]
    pages: NotRequired[builtins.list[str]]
    importer: NotRequired[builtins.list[str]]
    actions: NotRequired[builtins.list[str]]
    actions_macos: NotRequired[builtins.list[str]]
    codespaces: NotRequired[builtins.list[str]]
    dependabot: NotRequired[builtins.list[str]]
    copilot: NotRequired[builtins.list[str]]
    domains: NotRequired[ApiOverviewPropDomainsType]


class ApiOverviewPropSshKeyFingerprintsType(TypedDict):
    """ApiOverviewPropSshKeyFingerprints"""

    sha256_rsa: NotRequired[str]
    sha256_dsa: NotRequired[str]
    sha256_ecdsa: NotRequired[str]
    sha256_ed25519: NotRequired[str]


class ApiOverviewPropDomainsType(TypedDict):
    """ApiOverviewPropDomains"""

    website: NotRequired[builtins.list[str]]
    codespaces: NotRequired[builtins.list[str]]
    copilot: NotRequired[builtins.list[str]]
    packages: NotRequired[builtins.list[str]]
    actions: NotRequired[builtins.list[str]]
    actions_inbound: NotRequired[ApiOverviewPropDomainsPropActionsInboundType]
    artifact_attestations: NotRequired[
        ApiOverviewPropDomainsPropArtifactAttestationsType
    ]


class ApiOverviewPropDomainsPropActionsInboundType(TypedDict):
    """ApiOverviewPropDomainsPropActionsInbound"""

    full_domains: NotRequired[builtins.list[str]]
    wildcard_domains: NotRequired[builtins.list[str]]


class ApiOverviewPropDomainsPropArtifactAttestationsType(TypedDict):
    """ApiOverviewPropDomainsPropArtifactAttestations"""

    trust_domain: NotRequired[str]
    services: NotRequired[builtins.list[str]]


__all__ = (
    "ApiOverviewPropDomainsPropActionsInboundType",
    "ApiOverviewPropDomainsPropArtifactAttestationsType",
    "ApiOverviewPropDomainsType",
    "ApiOverviewPropSshKeyFingerprintsType",
    "ApiOverviewType",
)
