"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

import builtins
from typing import Union
from typing_extensions import NotRequired, TypedDict

from .group_0093 import (
    RepositoryRuleCreationType,
    RepositoryRuleDeletionType,
    RepositoryRuleNonFastForwardType,
    RepositoryRuleOneof15Type,
    RepositoryRuleOneof17Type,
    RepositoryRuleRequiredSignaturesType,
)
from .group_0094 import RepositoryRuleUpdateType
from .group_0096 import (
    RepositoryRuleOneof16Type,
    RepositoryRuleRequiredLinearHistoryType,
)
from .group_0097 import RepositoryRuleMergeQueueType
from .group_0099 import RepositoryRuleRequiredDeploymentsType
from .group_0102 import RepositoryRulePullRequestType
from .group_0104 import RepositoryRuleRequiredStatusChecksType
from .group_0106 import RepositoryRuleCommitMessagePatternType
from .group_0108 import RepositoryRuleCommitAuthorEmailPatternType
from .group_0110 import RepositoryRuleCommitterEmailPatternType
from .group_0112 import RepositoryRuleBranchNamePatternType
from .group_0114 import RepositoryRuleTagNamePatternType
from .group_0117 import RepositoryRuleWorkflowsType
from .group_0119 import RepositoryRuleCodeScanningType
from .group_0121 import RepositoryRuleOneof18Type
from .group_0787 import (
    WebhookRepositoryRulesetEditedPropChangesPropRulesPropUpdatedItemsType,
)


class WebhookRepositoryRulesetEditedPropChangesPropRulesType(TypedDict):
    """WebhookRepositoryRulesetEditedPropChangesPropRules"""

    added: NotRequired[
        builtins.list[
            Union[
                RepositoryRuleCreationType,
                RepositoryRuleUpdateType,
                RepositoryRuleDeletionType,
                RepositoryRuleRequiredLinearHistoryType,
                RepositoryRuleMergeQueueType,
                RepositoryRuleRequiredDeploymentsType,
                RepositoryRuleRequiredSignaturesType,
                RepositoryRulePullRequestType,
                RepositoryRuleRequiredStatusChecksType,
                RepositoryRuleNonFastForwardType,
                RepositoryRuleCommitMessagePatternType,
                RepositoryRuleCommitAuthorEmailPatternType,
                RepositoryRuleCommitterEmailPatternType,
                RepositoryRuleBranchNamePatternType,
                RepositoryRuleTagNamePatternType,
                RepositoryRuleOneof15Type,
                RepositoryRuleOneof16Type,
                RepositoryRuleOneof17Type,
                RepositoryRuleOneof18Type,
                RepositoryRuleWorkflowsType,
                RepositoryRuleCodeScanningType,
            ]
        ]
    ]
    deleted: NotRequired[
        builtins.list[
            Union[
                RepositoryRuleCreationType,
                RepositoryRuleUpdateType,
                RepositoryRuleDeletionType,
                RepositoryRuleRequiredLinearHistoryType,
                RepositoryRuleMergeQueueType,
                RepositoryRuleRequiredDeploymentsType,
                RepositoryRuleRequiredSignaturesType,
                RepositoryRulePullRequestType,
                RepositoryRuleRequiredStatusChecksType,
                RepositoryRuleNonFastForwardType,
                RepositoryRuleCommitMessagePatternType,
                RepositoryRuleCommitAuthorEmailPatternType,
                RepositoryRuleCommitterEmailPatternType,
                RepositoryRuleBranchNamePatternType,
                RepositoryRuleTagNamePatternType,
                RepositoryRuleOneof15Type,
                RepositoryRuleOneof16Type,
                RepositoryRuleOneof17Type,
                RepositoryRuleOneof18Type,
                RepositoryRuleWorkflowsType,
                RepositoryRuleCodeScanningType,
            ]
        ]
    ]
    updated: NotRequired[
        builtins.list[
            WebhookRepositoryRulesetEditedPropChangesPropRulesPropUpdatedItemsType
        ]
    ]


__all__ = ("WebhookRepositoryRulesetEditedPropChangesPropRulesType",)
