"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

import builtins
from typing import Literal, Union
from typing_extensions import NotRequired, TypedDict

from .group_0420 import UserEmailsResponseItemsType, UserNameResponseType
from .group_0421 import UserRoleItemsType


class UserResponseType(TypedDict):
    """UserResponse"""

    schemas: builtins.list[Literal["urn:ietf:params:scim:schemas:core:2.0:User"]]
    external_id: NotRequired[Union[str, None]]
    active: bool
    user_name: NotRequired[str]
    name: NotRequired[UserNameResponseType]
    display_name: NotRequired[Union[str, None]]
    emails: builtins.list[UserEmailsResponseItemsType]
    roles: NotRequired[builtins.list[UserRoleItemsType]]


__all__ = ("UserResponseType",)
