"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

import builtins
from typing_extensions import TypedDict

from .group_0029 import ActionsHostedRunnerMachineSpecType


class OrgsOrgActionsHostedRunnersMachineSizesGetResponse200Type(TypedDict):
    """OrgsOrgActionsHostedRunnersMachineSizesGetResponse200"""

    total_count: int
    machine_specs: builtins.list[ActionsHostedRunnerMachineSpecType]


__all__ = ("OrgsOrgActionsHostedRunnersMachineSizesGetResponse200Type",)
