"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

import builtins
from typing_extensions import TypedDict

from .group_0035 import OrganizationSimpleType


class EnterprisesEnterpriseActionsPermissionsOrganizationsGetResponse200Type(TypedDict):
    """EnterprisesEnterpriseActionsPermissionsOrganizationsGetResponse200"""

    total_count: float
    organizations: builtins.list[OrganizationSimpleType]


__all__ = ("EnterprisesEnterpriseActionsPermissionsOrganizationsGetResponse200Type",)
