"""DO NOT EDIT THIS FILE!

This file is automatically @generated by githubkit using the follow command:

bash ./scripts/run-codegen.sh

See https://github.com/github/rest-api-description for more information.
"""

from __future__ import annotations

import builtins
from typing import Literal, Union
from typing_extensions import NotRequired, TypedDict

from .group_0415 import MetaType
from .group_0420 import UserEmailsResponseItemsType, UserNameResponseType
from .group_0421 import UserRoleItemsType
from .group_0425 import ScimEnterpriseUserResponseAllof1PropGroupsItemsType


class ScimEnterpriseUserResponseType(TypedDict):
    """ScimEnterpriseUserResponse"""

    schemas: builtins.list[Literal["urn:ietf:params:scim:schemas:core:2.0:User"]]
    external_id: NotRequired[Union[str, None]]
    active: bool
    user_name: NotRequired[str]
    name: NotRequired[UserNameResponseType]
    display_name: NotRequired[Union[str, None]]
    emails: builtins.list[UserEmailsResponseItemsType]
    roles: NotRequired[builtins.list[UserRoleItemsType]]
    id: str
    groups: NotRequired[
        builtins.list[ScimEnterpriseUserResponseAllof1PropGroupsItemsType]
    ]
    meta: MetaType


class ScimEnterpriseUserListType(TypedDict):
    """ScimEnterpriseUserList"""

    schemas: builtins.list[
        Literal["urn:ietf:params:scim:api:messages:2.0:ListResponse"]
    ]
    total_results: int
    resources: builtins.list[ScimEnterpriseUserResponseType]
    start_index: int
    items_per_page: int


__all__ = (
    "ScimEnterpriseUserListType",
    "ScimEnterpriseUserResponseType",
)
